#Janela
LARGURA = 800
ALTURA = 600
TITULO = "Meu Jogo"

VELOCIDADE_JOGADOR = 5

QUANTIDADE_MOEDAS = 25

PONTOS_MOEDA = 1
PONTOS_MOEDA_ESPECIAL = 5

PONTOS_PERDIDOS_INIMIGO = 2
PONTOS_PERDIDOS_SUPER = 5